// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSzzjcVEa8-9c7xquzbi5Q2eBebCPup-M',
    appId: '1:763448143772:web:99de90a4c03a5ca6412259',
    messagingSenderId: '763448143772',
    projectId: 'fir-auth-8a735',
    authDomain: 'fir-auth-8a735.firebaseapp.com',
    storageBucket: 'fir-auth-8a735.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5qNEwdkjilvje1kReCvrr8_fyCqfgTpU',
    appId: '1:763448143772:android:c5763680aaaad714412259',
    messagingSenderId: '763448143772',
    projectId: 'fir-auth-8a735',
    storageBucket: 'fir-auth-8a735.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1edBm6yaFv7rFY2nX962F5NOpuTdboLw',
    appId: '1:763448143772:ios:6aa6a8c7ba8dd987412259',
    messagingSenderId: '763448143772',
    projectId: 'fir-auth-8a735',
    storageBucket: 'fir-auth-8a735.appspot.com',
    iosBundleId: 'com.example.takingNotesFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1edBm6yaFv7rFY2nX962F5NOpuTdboLw',
    appId: '1:763448143772:ios:3116bc870774c41f412259',
    messagingSenderId: '763448143772',
    projectId: 'fir-auth-8a735',
    storageBucket: 'fir-auth-8a735.appspot.com',
    iosBundleId: 'com.example.takingNotesFirebaseApp.RunnerTests',
  );
}
